-- File: 04_Categories.sql

SET IDENTITY_INSERT [Categories] ON;
GO
INSERT INTO [Categories] ([Id], [Name], [Slug], [Description], [ImageUrl], [Icon], [SortOrder], [IsActive], [ParentCategoryId], [CreatedAt]) VALUES (1, N'Hoa Sinh Nhật', N'hoa-sinh-nhat', N'Các mẫu hoa chúc mừng sinh nhật đẹp, ý nghĩa dành tặng người thân, bạn bè, đồng nghiệp', N'https://png.pngtree.com/png-clipart/20220719/original/pngtree-happy-birthday-frame-border-post-cartoon-png-png-image_8364102.png', NULL, 1, 1, NULL, N'2026-08-11 11:32:03.840');
INSERT INTO [Categories] ([Id], [Name], [Slug], [Description], [ImageUrl], [Icon], [SortOrder], [IsActive], [ParentCategoryId], [CreatedAt]) VALUES (2, N'Hoa Khai Trương', N'hoa-khai-truong', N'Kệ hoa, lẵng hoa chúc mừng khai trương hồng phát, may mắn và tài lộc', N'https://cayxanhtanthuy.com/wp-content/uploads/2023/05/hoa-chuc-mung-khai-truong-1.jpg', NULL, 2, 1, NULL, N'2026-08-11 11:32:03.840');
INSERT INTO [Categories] ([Id], [Name], [Slug], [Description], [ImageUrl], [Icon], [SortOrder], [IsActive], [ParentCategoryId], [CreatedAt]) VALUES (3, N'Hoa Cưới & Cho Cô Dâu', N'hoa-cuoi-cho-co-dau', N'Hoa cầm tay cô dâu, hoa xe cưới, hoa trang trí tiệc cưới sang trọng', N'https://tse3.mm.bing.net/th/id/OIP.F53HvaAmBJFMHVMxgZ_3uQHaHa?r=0&rs=1&pid=ImgDetMain&o=7&rm=3', NULL, 3, 1, NULL, N'2026-08-11 11:32:03.840');
INSERT INTO [Categories] ([Id], [Name], [Slug], [Description], [ImageUrl], [Icon], [SortOrder], [IsActive], [ParentCategoryId], [CreatedAt]) VALUES (4, N'Hoa Chia Buồn & Tang Lễ', N'hoa-chia-buon-tang-le', N'Vòng hoa, kệ hoa viếng tang lễ thể hiện sự kính trọng và chia buồn sâu sắc', N'https://via.placeholder.com/300x300?text=Hoa+Chia+Buon', N'fa-ribbon', 4, 1, NULL, N'2026-08-11 11:32:03.840');
INSERT INTO [Categories] ([Id], [Name], [Slug], [Description], [ImageUrl], [Icon], [SortOrder], [IsActive], [ParentCategoryId], [CreatedAt]) VALUES (5, N'Hoa Theo Loại', N'hoa-theo-loai', N'Các sản phẩm phân loại theo từng dòng hoa như Hoa Hồng, Hoa Hướng Dương, Hoa Lan...', N'https://via.placeholder.com/300x300?text=Hoa+Theo+Loai', N'fa-spa', 5, 1, NULL, N'2026-08-11 11:32:03.840');
INSERT INTO [Categories] ([Id], [Name], [Slug], [Description], [ImageUrl], [Icon], [SortOrder], [IsActive], [ParentCategoryId], [CreatedAt]) VALUES (6, N'Hoa Thiết Kế Theo Kiểu Dáng', N'hoa-thiet-ke-theo-kieu-dang', N'Bó hoa, giỏ hoa, lẵng hoa, hộp hoa, bình hoa nghệ thuật', N'https://via.placeholder.com/300x300?text=Kieu+Dang+Hoa', N'fa-shopping-bag', 6, 1, NULL, N'2026-08-11 11:32:03.840');
INSERT INTO [Categories] ([Id], [Name], [Slug], [Description], [ImageUrl], [Icon], [SortOrder], [IsActive], [ParentCategoryId], [CreatedAt]) VALUES (7, N'Hoa Chủ Đề Dịp Lễ', N'hoa-chu-de-dip-le', N'Hoa dành cho các ngày lễ Valentine 14/2, 8/3, 20/10, Ngày của Mẹ, Giáng Sinh', N'https://via.placeholder.com/300x300?text=Hoa+Dip+Le', N'fa-calendar-alt', 7, 1, NULL, N'2026-08-11 11:32:03.840');
INSERT INTO [Categories] ([Id], [Name], [Slug], [Description], [ImageUrl], [Icon], [SortOrder], [IsActive], [ParentCategoryId], [CreatedAt]) VALUES (8, N'Hoa Sáp & Hoa Khô', N'hoa-sap-hoa-kho', N'Hoa sáp thơm, hoa khô giữ được lâu năm, thiết kế tinh tế', N'https://via.placeholder.com/300x300?text=Hoa+Sap+Kho', N'fa-snowflake', 8, 1, NULL, N'2026-08-11 11:32:03.840');
INSERT INTO [Categories] ([Id], [Name], [Slug], [Description], [ImageUrl], [Icon], [SortOrder], [IsActive], [ParentCategoryId], [CreatedAt]) VALUES (9, N'Cây Cảnh & Chậu Hoa Để Bàn', N'cay-canh-chau-hoa-de-ban', N'Cây sen đá, cây phong thủy, chậu hoa nhỏ trang trí bàn làm việc', N'https://via.placeholder.com/300x300?text=Cay+Canh+Mini', N'fa-seedling', 9, 1, NULL, N'2026-08-11 11:32:03.840');
INSERT INTO [Categories] ([Id], [Name], [Slug], [Description], [ImageUrl], [Icon], [SortOrder], [IsActive], [ParentCategoryId], [CreatedAt]) VALUES (10, N'Quà Tặng Kèm', N'qua-tang-kem', N'Gấu bông, bánh kem, thiệp chúc mừng, socola tặng kèm hoa', N'https://via.placeholder.com/300x300?text=Qua+Tang+Kem', N'fa-gift', 10, 1, NULL, N'2026-08-11 11:32:03.840');
INSERT INTO [Categories] ([Id], [Name], [Slug], [Description], [ImageUrl], [Icon], [SortOrder], [IsActive], [ParentCategoryId], [CreatedAt]) VALUES (11, N'Hoa Sinh Nhật Tặng Bạn Gái', N'hoa-sinh-nhat-tang-ban-gai', N'Các mẫu hoa lãng mạn, ngọt ngào dành tặng người yêu, bạn gái', N'https://via.placeholder.com/300x300?text=Hoa+Tang+Ban+Gai', N'fa-heart', 1, 1, 1, N'2026-08-11 11:32:03.840');
INSERT INTO [Categories] ([Id], [Name], [Slug], [Description], [ImageUrl], [Icon], [SortOrder], [IsActive], [ParentCategoryId], [CreatedAt]) VALUES (12, N'Hoa Sinh Nhật Tặng Mẹ', N'hoa-sinh-nhat-tang-me', N'Hoa kính yêu, lòng biết ơn gửi trao đến Mẹ', N'https://via.placeholder.com/300x300?text=Hoa+Tang+Me', N'fa-user-nurse', 2, 1, 1, N'2026-08-11 11:32:03.840');
INSERT INTO [Categories] ([Id], [Name], [Slug], [Description], [ImageUrl], [Icon], [SortOrder], [IsActive], [ParentCategoryId], [CreatedAt]) VALUES (13, N'Hoa Sinh Nhật Tặng Sếp & Đối Tác', N'hoa-sinh-nhat-tang-sep', N'Các thiết kế hoa sang trọng, tinh tế tặng cấp trên và đối tác kinh doanh', N'https://via.placeholder.com/300x300?text=Hoa+Tang+Sep', N'fa-user-tie', 3, 1, 1, N'2026-08-11 11:32:03.840');
INSERT INTO [Categories] ([Id], [Name], [Slug], [Description], [ImageUrl], [Icon], [SortOrder], [IsActive], [ParentCategoryId], [CreatedAt]) VALUES (14, N'Hoa Sinh Nhật Nam Giới', N'hoa-sinh-nhat-nam-gioi', N'Mẫu hoa tông màu trầm, thanh lịch dành tặng bạn nam, chồng, cha', N'https://via.placeholder.com/300x300?text=Hoa+Nam+Gioi', N'fa-mars', 4, 1, 1, N'2026-08-11 11:32:03.840');
INSERT INTO [Categories] ([Id], [Name], [Slug], [Description], [ImageUrl], [Icon], [SortOrder], [IsActive], [ParentCategoryId], [CreatedAt]) VALUES (15, N'Kệ Hoa Khai Trương 2 Tầng', N'ke-hoa-khai-truong-2-tang', N'Kệ hoa đứng 2 tầng hoành tráng, rực rỡ', N'https://via.placeholder.com/300x300?text=Ke+Hoa+2+Tang', N'fa-layer-group', 1, 1, 2, N'2026-08-11 11:32:03.840');
INSERT INTO [Categories] ([Id], [Name], [Slug], [Description], [ImageUrl], [Icon], [SortOrder], [IsActive], [ParentCategoryId], [CreatedAt]) VALUES (16, N'Kệ Hoa Khai Trương 3 Tầng', N'ke-hoa-khai-truong-3-tang', N'Kệ hoa cao cấp 3 tầng mừng khai trương công ty, cửa hàng', N'https://via.placeholder.com/300x300?text=Ke+Hoa+3+Tang', N'fa-align-justify', 2, 1, 2, N'2026-08-11 11:32:03.840');
INSERT INTO [Categories] ([Id], [Name], [Slug], [Description], [ImageUrl], [Icon], [SortOrder], [IsActive], [ParentCategoryId], [CreatedAt]) VALUES (17, N'Lẵng Hoa Khai Trương Để Bàn', N'lang-hoa-khai-truong-de-ban', N'Lẵng hoa nhỏ gọn đặt bàn lễ tân, bàn làm việc dịp khai trương', N'https://via.placeholder.com/300x300?text=Lang+Hoa+De+Ban', N'fa-table', 3, 1, 2, N'2026-08-11 11:32:03.840');
INSERT INTO [Categories] ([Id], [Name], [Slug], [Description], [ImageUrl], [Icon], [SortOrder], [IsActive], [ParentCategoryId], [CreatedAt]) VALUES (18, N'Hoa Cầm Tay Cô Dâu', N'hoa-cam-tay-co-dau', N'Bó hoa tay cầm tinh tế cho cô dâu trong ngày trọng đại', N'https://via.placeholder.com/300x300?text=Hoa+Cam+Tay', N'fa-female', 1, 1, 3, N'2026-08-11 11:32:03.840');
INSERT INTO [Categories] ([Id], [Name], [Slug], [Description], [ImageUrl], [Icon], [SortOrder], [IsActive], [ParentCategoryId], [CreatedAt]) VALUES (19, N'Hoa Cài Áo Chú Rể', N'hoa-cai-ao-chu-re', N'Hoa nhỏ cài áo đồng bộ với hoa cầm tay cô dâu', N'https://via.placeholder.com/300x300?text=Hoa+Cai+Ao', N'fa-user-astronaut', 2, 1, 3, N'2026-08-11 11:32:03.840');
INSERT INTO [Categories] ([Id], [Name], [Slug], [Description], [ImageUrl], [Icon], [SortOrder], [IsActive], [ParentCategoryId], [CreatedAt]) VALUES (20, N'Hoa Trang Trí Xe Cưới', N'hoa-trang-tri-xe-cuoi', N'Bộ hoa trang trí đầu xe, đuôi xe đón dâu sang trọng', N'https://via.placeholder.com/300x300?text=Hoa+Xe+Cuoi', N'fa-car', 3, 1, 3, N'2026-08-11 11:32:03.840');
INSERT INTO [Categories] ([Id], [Name], [Slug], [Description], [ImageUrl], [Icon], [SortOrder], [IsActive], [ParentCategoryId], [CreatedAt]) VALUES (21, N'Vòng Hoa Tang Lễ Truyền Thống', N'vong-hoa-tang-le-truyen-thong', N'Vòng hoa viếng kiểu truyền thống màu vàng, đỏ, tím', N'https://via.placeholder.com/300x300?text=Vong+Hoa+Truyen+Thong', N'fa-circle-notch', 1, 1, 4, N'2026-08-11 11:32:03.840');
INSERT INTO [Categories] ([Id], [Name], [Slug], [Description], [ImageUrl], [Icon], [SortOrder], [IsActive], [ParentCategoryId], [CreatedAt]) VALUES (22, N'Kệ Hoa Viếng Hiện Đại', N'ke-hoa-vieng-hien-dai', N'Kệ hoa chia buồn thiết kế phong cách hiện đại, thanh lịch', N'https://via.placeholder.com/300x300?text=Ke+Hoa+Hien+Dai', N'fa-square', 2, 1, 4, N'2026-08-11 11:32:03.840');
INSERT INTO [Categories] ([Id], [Name], [Slug], [Description], [ImageUrl], [Icon], [SortOrder], [IsActive], [ParentCategoryId], [CreatedAt]) VALUES (23, N'Hoa Chia Buồn Tông Trắng', N'hoa-chia-buon-tong-trang', N'Hoa viếng sử dụng hoa cúc trắng, lan trắng, hồng trắng', N'https://via.placeholder.com/300x300?text=Hoa+Vieng+Trang', N'fa-feather', 3, 1, 4, N'2026-08-11 11:32:03.840');
INSERT INTO [Categories] ([Id], [Name], [Slug], [Description], [ImageUrl], [Icon], [SortOrder], [IsActive], [ParentCategoryId], [CreatedAt]) VALUES (24, N'Hoa Hồng', N'hoa-hong', N'Hoa hồng đỏ, hồng phấn, hồng kem, hồng ecuador...', N'https://via.placeholder.com/300x300?text=Hoa+Hong', N'fa-fan', 1, 1, 5, N'2026-08-11 11:32:03.840');
INSERT INTO [Categories] ([Id], [Name], [Slug], [Description], [ImageUrl], [Icon], [SortOrder], [IsActive], [ParentCategoryId], [CreatedAt]) VALUES (25, N'Hoa Hướng Dương', N'hoa-huong-duong', N'Hoa hướng dương biểu tượng cho niềm tin, hy vọng và may mắn', N'https://via.placeholder.com/300x300?text=Hoa+Huong+Duong', N'fa-sun', 2, 1, 5, N'2026-08-11 11:32:03.840');
INSERT INTO [Categories] ([Id], [Name], [Slug], [Description], [ImageUrl], [Icon], [SortOrder], [IsActive], [ParentCategoryId], [CreatedAt]) VALUES (26, N'Hoa Lan Hồ Điệp', N'hoa-lan-ho-diep', N'Chậu lan hồ điệp sang trọng tặng khai trương, tân gia, Tết', N'https://via.placeholder.com/300x300?text=Lan+Ho+Diep', N'fa-leaf', 3, 1, 5, N'2026-08-11 11:32:03.840');
INSERT INTO [Categories] ([Id], [Name], [Slug], [Description], [ImageUrl], [Icon], [SortOrder], [IsActive], [ParentCategoryId], [CreatedAt]) VALUES (27, N'Hoa Cẩm Tú Cầu', N'hoa-cam-tu-cau', N'Bó hoa cẩm tú cầu dịu dàng, nhẹ nhàng', N'https://via.placeholder.com/300x300?text=Hoa+Cam+Tu+Cau', N'fa-globe', 4, 1, 5, N'2026-08-11 11:32:03.840');
INSERT INTO [Categories] ([Id], [Name], [Slug], [Description], [ImageUrl], [Icon], [SortOrder], [IsActive], [ParentCategoryId], [CreatedAt]) VALUES (28, N'Hoa Baby', N'hoa-baby', N'Hoa baby trắng, baby hồng chùm bồng bềnh như mây', N'https://via.placeholder.com/300x300?text=Hoa+Baby', N'fa-cloud', 5, 1, 5, N'2026-08-11 11:32:03.840');
INSERT INTO [Categories] ([Id], [Name], [Slug], [Description], [ImageUrl], [Icon], [SortOrder], [IsActive], [ParentCategoryId], [CreatedAt]) VALUES (29, N'Hoa Tulip', N'hoa-tulip', N'Hoa tulip nhập khẩu Hà Lan kiêu sa, quý phái', N'https://via.placeholder.com/300x300?text=Hoa+Tulip', N'fa-seedling', 6, 1, 5, N'2026-08-11 11:32:03.840');
INSERT INTO [Categories] ([Id], [Name], [Slug], [Description], [ImageUrl], [Icon], [SortOrder], [IsActive], [ParentCategoryId], [CreatedAt]) VALUES (30, N'Hoa Cúc Tana & Matricaria', N'hoa-cuc-tana-matricaria', N'Hoa cúc Tana nhỏ nhắn, mộc mạc, dễ thương', N'https://via.placeholder.com/300x300?text=Cuc+Tana', N'fa-asterisk', 7, 1, 5, N'2026-08-11 11:32:03.840');
INSERT INTO [Categories] ([Id], [Name], [Slug], [Description], [ImageUrl], [Icon], [SortOrder], [IsActive], [ParentCategoryId], [CreatedAt]) VALUES (31, N'Bó Hoa Tươi', N'bo-hoa-tuoi', N'Các thiết kế bó hoa tròn, bó hoa dài, bó hoa khổng lồ', N'https://via.placeholder.com/300x300?text=Bo+Hoa', N'fa-archive', 1, 1, 6, N'2026-08-11 11:32:03.840');
INSERT INTO [Categories] ([Id], [Name], [Slug], [Description], [ImageUrl], [Icon], [SortOrder], [IsActive], [ParentCategoryId], [CreatedAt]) VALUES (32, N'Giỏ Hoa & Lẵng Hoa', N'gio-hoa-lang-hoa', N'Giỏ hoa mây, lẵng hoa tươi cắm nghệ thuật', N'https://via.placeholder.com/300x300?text=Gio+Hoa', N'fa-shopping-basket', 2, 1, 6, N'2026-08-11 11:32:03.840');
INSERT INTO [Categories] ([Id], [Name], [Slug], [Description], [ImageUrl], [Icon], [SortOrder], [IsActive], [ParentCategoryId], [CreatedAt]) VALUES (33, N'Hộp Hoa Mica & Hộp Giấy', N'hop-hoa-mica-hop-giay', N'Hoa cắm trong hộp mica trong suốt hoặc hộp quà sang trọng', N'https://via.placeholder.com/300x300?text=Hop+Hoa', N'fa-box-open', 3, 1, 6, N'2026-08-11 11:32:03.840');
INSERT INTO [Categories] ([Id], [Name], [Slug], [Description], [ImageUrl], [Icon], [SortOrder], [IsActive], [ParentCategoryId], [CreatedAt]) VALUES (34, N'Bình Hoa Cắm Sẵn', N'binh-hoa-cam-san', N'Bình thủy tinh, bình gốm cắm hoa tươi hoàn chỉnh trang trí nhà cửa', N'https://via.placeholder.com/300x300?text=Binh+Hoa', N'fa-glass-martini-alt', 4, 1, 6, N'2026-08-11 11:32:03.840');
INSERT INTO [Categories] ([Id], [Name], [Slug], [Description], [ImageUrl], [Icon], [SortOrder], [IsActive], [ParentCategoryId], [CreatedAt]) VALUES (35, N'Hoa Valentine 14/2', N'hoa-valentine-14-2', N'Bó hoa hồng đỏ lãng mạn tình yêu Valentine', N'https://via.placeholder.com/300x300?text=Hoa+Valentine', N'fa-heart-broken', 1, 1, 7, N'2026-08-11 11:32:03.840');
INSERT INTO [Categories] ([Id], [Name], [Slug], [Description], [ImageUrl], [Icon], [SortOrder], [IsActive], [ParentCategoryId], [CreatedAt]) VALUES (36, N'Hoa Quốc Tế Phụ Nữ 8/3', N'hoa-quoc-te-phu-nu-8-3', N'Hoa chúc mừng dành tôn vinh phái đẹp ngày 8/3', N'https://via.placeholder.com/300x300?text=Hoa+8-3', N'fa-venus', 2, 1, 7, N'2026-08-11 11:32:03.840');
INSERT INTO [Categories] ([Id], [Name], [Slug], [Description], [ImageUrl], [Icon], [SortOrder], [IsActive], [ParentCategoryId], [CreatedAt]) VALUES (37, N'Hoa Phụ Nữ Việt Nam 20/10', N'hoa-phu-nu-viet-nam-20-10', N'Các mẫu hoa tươi thắm tri ân phụ nữ Việt Nam 20/10', N'https://via.placeholder.com/300x300?text=Hoa+20-10', N'fa-award', 3, 1, 7, N'2026-08-11 11:32:03.840');
INSERT INTO [Categories] ([Id], [Name], [Slug], [Description], [ImageUrl], [Icon], [SortOrder], [IsActive], [ParentCategoryId], [CreatedAt]) VALUES (38, N'Hoa Nhà Giáo Việt Nam 20/11', N'hoa-nha-giao-viet-nam-20-11', N'Hoa tươi tri ân thầy cô giáo nhân ngày 20/11', N'https://via.placeholder.com/300x300?text=Hoa+20-11', N'fa-graduation-cap', 4, 1, 7, N'2026-08-11 11:32:03.840');
INSERT INTO [Categories] ([Id], [Name], [Slug], [Description], [ImageUrl], [Icon], [SortOrder], [IsActive], [ParentCategoryId], [CreatedAt]) VALUES (39, N'Bó Hoa Sáp Thơm', N'bo-hoa-sap-thom', N'Hoa sáp hương thơm nhẹ nhàng, giữ màu sắc lâu', N'https://via.placeholder.com/300x300?text=Hoa+Sap', N'fa-air-freshener', 1, 1, 8, N'2026-08-11 11:32:03.840');
INSERT INTO [Categories] ([Id], [Name], [Slug], [Description], [ImageUrl], [Icon], [SortOrder], [IsActive], [ParentCategoryId], [CreatedAt]) VALUES (40, N'Hộp Hoa Sáp Trái Tim', N'hop-hoa-sap-trai-tim', N'Hộp quà xếp hoa sáp hình trái tim ngọt ngào', N'https://via.placeholder.com/300x300?text=Hop+Hoa+Sap', N'fa-heart', 2, 1, 8, N'2026-08-11 11:32:03.840');
INSERT INTO [Categories] ([Id], [Name], [Slug], [Description], [ImageUrl], [Icon], [SortOrder], [IsActive], [ParentCategoryId], [CreatedAt]) VALUES (41, N'Hoa Baby Khô & Hoa Lavender Khô', N'hoa-baby-kho-lavender-kho', N'Hoa khô nhập khẩu giữ màu tự nhiên, hương dịu nhẹ', N'https://via.placeholder.com/300x300?text=Hoa+Kho', N'fa-mortar-pestle', 3, 1, 8, N'2026-08-11 11:32:03.840');
INSERT INTO [Categories] ([Id], [Name], [Slug], [Description], [ImageUrl], [Icon], [SortOrder], [IsActive], [ParentCategoryId], [CreatedAt]) VALUES (42, N'Chậu Sen Đá & Xương Rồng', N'chau-sen-da-xuong-rong', N'Các tiểu cảnh sen đá xinh xắn dễ chăm sóc', N'https://via.placeholder.com/300x300?text=Sen+Da', N'fa-stroopwafel', 1, 1, 9, N'2026-08-11 11:32:03.840');
INSERT INTO [Categories] ([Id], [Name], [Slug], [Description], [ImageUrl], [Icon], [SortOrder], [IsActive], [ParentCategoryId], [CreatedAt]) VALUES (43, N'Cây Phong Thủy Để Bàn', N'cay-phong-thuy-de-ban', N'Cây Kim Tiền, Kim Ngân, Trầu Bà mang lại may mắn, tài lộc', N'https://via.placeholder.com/300x300?text=Cay+Phong+Thuy', N'fa-coins', 2, 1, 9, N'2026-08-11 11:32:03.840');
INSERT INTO [Categories] ([Id], [Name], [Slug], [Description], [ImageUrl], [Icon], [SortOrder], [IsActive], [ParentCategoryId], [CreatedAt]) VALUES (44, N'Gấu Bông Nhỏ Tặng Kèm', N'gau-bong-nho-tang-kem', N'Gấu teddy, gấu nhỏ đáng yêu mua kèm bó hoa', N'https://via.placeholder.com/300x300?text=Gau+Bong', N'fa-smile-beam', 1, 1, 10, N'2026-08-11 11:32:03.840');
INSERT INTO [Categories] ([Id], [Name], [Slug], [Description], [ImageUrl], [Icon], [SortOrder], [IsActive], [ParentCategoryId], [CreatedAt]) VALUES (45, N'Bánh Kem Sinh Nhật', N'banh-kem-sinh-nhat', N'Bánh sinh nhật rau câu, bánh kem sữa tươi tươi mới mỗi ngày', N'https://via.placeholder.com/300x300?text=Banh+Kem', N'fa-birthday-cake', 2, 1, 10, N'2026-08-11 11:32:03.840');
INSERT INTO [Categories] ([Id], [Name], [Slug], [Description], [ImageUrl], [Icon], [SortOrder], [IsActive], [ParentCategoryId], [CreatedAt]) VALUES (46, N'Socola Valentine & Quà Tặng', N'socola-valentine-qua-tang', N'Hộp socola thanh ngọt tặng kèm hoa tươi', N'https://via.placeholder.com/300x300?text=Socola', N'fa-cookie-bite', 3, 1, 10, N'2026-08-11 11:32:03.840');
INSERT INTO [Categories] ([Id], [Name], [Slug], [Description], [ImageUrl], [Icon], [SortOrder], [IsActive], [ParentCategoryId], [CreatedAt]) VALUES (47, N'Thiệp Chúc Mừng Lời Chúc', N'thiep-chuc-mung-loi-chuc', N'Thiệp in tay, thiệp handmade viết lời chúc ý nghĩa', N'https://via.placeholder.com/300x300?text=Thiep+Chuc+Mung', N'fa-envelope-open-text', 4, 1, 10, N'2026-08-11 11:32:03.840');
INSERT INTO [Categories] ([Id], [Name], [Slug], [Description], [ImageUrl], [Icon], [SortOrder], [IsActive], [ParentCategoryId], [CreatedAt]) VALUES (48, N'Hoa Chơi Tết & Nụ Tầm Xuân', N'hoa-choi-tet-nu-tam-xuan', N'Nụ tầm xuân, hoa đào, hoa mai, chậu hoa lan chưng Tết', N'https://cdn.s99.vn/ss1/prod/product/f9c8789deaa72623b02897ad162235d4.jpg', NULL, 1, 1, NULL, N'2026-08-11 11:32:03.840');
INSERT INTO [Categories] ([Id], [Name], [Slug], [Description], [ImageUrl], [Icon], [SortOrder], [IsActive], [ParentCategoryId], [CreatedAt]) VALUES (49, N'Dịch Vụ Trang Trí Hoa Sự Kiện', N'dich-vu-trang-tri-hoa-su-kien', N'Nhận thiết kế trang trí hoa tươi hội nghị, tiệc gala, sinh nhật lớn', N'https://png.pngtree.com/png-clipart/20220311/ourlarge/pngtree-micro-three-dimensional-metal-plant-flower-plum-blossom-frame-png-image_4415785.png', NULL, 2, 1, NULL, N'2026-08-11 11:32:03.840');
INSERT INTO [Categories] ([Id], [Name], [Slug], [Description], [ImageUrl], [Icon], [SortOrder], [IsActive], [ParentCategoryId], [CreatedAt]) VALUES (50, N'Gói Đăng Ký Hoa Định Kỳ', N'goi-dang-ky-hoa-dinh-ky', N'Giao hoa tươi định kỳ hàng tuần cho văn phòng, khách sạn, căn hộ', N'https://via.placeholder.com/300x300?text=Hoa+Dinh+Ky', N'fa-sync-alt', 3, 1, NULL, N'2026-08-11 11:32:03.840');
SET IDENTITY_INSERT [Categories] OFF;
GO

